# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-27 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='abstract',
            field=models.CharField(default='', max_length=255),
        ),
    ]
